Feature/product page
binary-hideout/elecritic pull request #22
Opened 2020-11-09 23:30 UTC by Diegobr21

Product Page now has/does:
*Product Card
*Random reviews generated from ReviewService.cs
*EditForm to create reviews (not saved just UI with DataAnnotations)

2020-11-09 23:53 UTC, netotz requested changes
In addition to the other comments, I suggest the following changes:

- Add docstrings to classes, properties and methods to explain why they are there and their purpose
- Remove unnecessary imports and clean up code
- Remove `@code { }` blocks from .razor files

2020-11-09 23:53 UTC, netotz commented on Elecritic/Pages/ProductPage.razor.cs
> +        public ReviewService reviewService { get; set; }
rename property to match naming conventions to `ReviewService`

2020-11-09 23:53 UTC, netotz commented on Elecritic/Pages/ProductPage.razor.cs
> +        public ReviewModel review { get; set; }
rename property to match naming conventions to `Review` or `ReviewModel`

2020-11-10 03:39 UTC, netotz approved these changes

2020-11-10 03:40 UTC, netotz approved these changes
nice!

2020-11-10 03:40 UTC, merged

2020-11-10 03:57 UTC, Diegobr21 commented
> nice!

Thanks  senpai