feat<Login,Register,Host,CSS,imports> add the login and  register interface...
binary-hideout/elecritic pull request #24
Opened 2020-11-11 22:28 UTC by Robertudo

..., their respective models and the radzen library

2020-11-11 22:52 UTC, netotz requested changes
Move all the `@code { }` blocks to code behind files (`.razor.cs`)

2020-11-13 22:27 UTC, Robertudo commented
Do you accept my changes? UwU

2020-11-14 00:27 UTC, netotz requested changes

2020-11-14 00:27 UTC, netotz commented on Elecritic/Pages/Login.razor.cs
> +        LoginRequest model = new LoginRequest();
`private LoginRequest Model { get; set; } = new LoginRequest();`

2020-11-14 00:27 UTC, netotz commented on Elecritic/Pages/Register.razor.cs
> +        RegisterRequest model = new RegisterRequest();
`private RegisterRequest Model { get; set; } = new RegisterRequest();`

2020-11-14 01:44 UTC, netotz approved these changes, later dismissed
nice!

2020-11-14 05:50 UTC, Diegobr21 submitted a review, later dismissed
Nice! We need to review if its necessary for those tasks to run asynchronously as they aren´t currently

2020-11-14 06:44 UTC, netotz commented
> We need to review if its necessary for those tasks to run asynchronously as they aren´t currently

@Diegobr21 I think they'll work well when the database calls get implemented

2020-11-14 06:53 UTC, netotz approved these changes

2020-11-14 06:53 UTC, merged